properties([
    parameters([
    string(defaultValue: 'pem', description: 'cloudformation key pair to use', name: 'KeyName')
    ]),
    pipelineTriggers([])
])
pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('d3cf4e66-1c8b-412a-9e5e-6c2f568f7d81')
        AWS_SECRET_ACCESS_KEY = credentials('07db0801-b4ad-4fb2-ae2f-1abd50d2b438')

    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Create Infrastructure') {
            steps {          		
                script {
                    sh """
                        aws --no-verify cloudformation deploy --template-file ${WORKSPACE}/Lab-2/code-samples/cf-infrastructure.json \
                        --stack-name lab-2 \
                        --parameter-overrides KeyName=${KeyName} \
                        --region us-east-1
                        """
                }								
            }
        }
        
       
    }
}
