AWSTemplateFormatVersion: '2010-09-09'
Description: "Template for installing Jenkins on Linux *delete when done*"

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install Jenkins
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk-devel: []
              git: []
          files:
            '/etc/cfn/cfn-hup.conf':
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: '000400'
              owner: root
              group: root
            '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.JenkinsServer.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack=${AWS::StackName} --region=${AWS::Region} --resource=JenkinsServer 
                runas=root
              mode: '000400'
              owner: root
              group: root
            '/var/lib/jenkins/config.xml':
              content: |
                <?xml version='1.1' encoding='UTF-8'?>
                <hudson>
                  <disabledAdministrativeMonitors/>
                  <version>2.147</version>
                  <installStateName>NEW</installStateName>
                  <numExecutors>2</numExecutors>
                  <mode>NORMAL</mode>
                  <useSecurity>false</useSecurity>
                  <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
                    <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
                  </authorizationStrategy>
                  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
                    <disableSignup>true</disableSignup>
                    <enableCaptcha>false</enableCaptcha>
                  </securityRealm>
                  <disableRememberMe>false</disableRememberMe>
                  <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
                  <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULL_NAME}</workspaceDir>
                  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
                  <jdks/>
                  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
                  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
                  <clouds/>
                  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
                  <views>
                    <hudson.model.AllView>
                      <owner class="hudson" reference="../../.."/>
                      <name>all</name>
                      <filterExecutors>false</filterExecutors>
                      <filterQueue>false</filterQueue>
                      <properties class="hudson.model.View$PropertyList"/>
                    </hudson.model.AllView>
                  </views>
                  <primaryView>all</primaryView>
                  <slaveAgentPort>-1</slaveAgentPort>
                  <label></label>
                  <crumbIssuer class="hudson.security.csrf.DefaultCrumbIssuer">
                    <excludeClientIPFromCrumb>false</excludeClientIPFromCrumb>
                  </crumbIssuer>
                  <nodeProperties/>
                  <globalNodeProperties/>
                </hudson>
              mode: '000755'
              owner: root
              group: root
          commands:
            download_repo:
              command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat/jenkins.repo
            configure_key:
              command: rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
            install_jenkins:
              command: yum install jenkins -y 
          services:
            sysvinit:
              jenkins:
                enabled: true
                ensureRunning: true
                #commands: 
                #  - sed -i 's|<useSecurity>true|<useSecurity>false|g' /var/lib/jenkins/config.xml
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - '/etc/cfn/cfn-hup.conf'
                  - '/etc/cfn/hooks.d/cfn-auto-reloader.conf'   
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref 'JenkinsSecurityGroup'
      ImageId: ami-0922553b7b0369273
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Get the latest CloudFormation package
          yum update -y aws-cfn-bootstrap
          # Start cfn-init
          /opt/aws/bin/cfn-init -v -c default --stack ${AWS::StackId} --resource JenkinsServer --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
          # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
          /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
          # All done so signal success
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource JenkinsServer --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M

  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: rules for opening the web and ssh ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

Outputs:
  JenkinsURL:
    Description: URL for Jenkins
    Value: !Join
      - ''
      - - http://
        - !GetAtt 'JenkinsServer.PublicIp'
        - :8080
